# Generated by Django 3.1.2 on 2020-10-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalFormatTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=9)),
                ('original_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_conversion.originalformat')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalFormatExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('original_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_conversion.originalformat')),
            ],
        ),
    ]
