# Generated by Django 3.1.2 on 2020-10-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalformattier',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
