# Generated by Django 3.1.2 on 2020-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_conversion', '0002_auto_20201003_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalformat',
            name='singular_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
