# Generated by Django 3.0.4 on 2020-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocking', '0002_brand_model_phoneunlock_repairtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
