# Generated by Django 3.0.4 on 2020-03-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlocking', '0003_network_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='network',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='network',
            name='image',
        ),
        migrations.DeleteModel(
            name='NetworkAlternativeName',
        ),
        migrations.AddField(
            model_name='networkname',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlocking.Network'),
        ),
    ]
